name: brainy-ae
static_sites:
- name: web
  source_dir: /
  github:
    repo: softdevfz/brainy.ae---ai-powered-tools-for-your-business
    branch: main
  build_command: npm run build
  output_dir: dist
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
domains:
- domain: brainy.ae
  type: PRIMARY
- domain: www.brainy.ae
  type: ALIAS 